### PR TITLE
Use window.zooniverse when possible

### PR DESCRIPTION
**Pull request by parrish**
Instead of overriding customized components, this causes `require`s to consistently prefer already defined modules.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Works fine in a quick test with Science Gossip. I still need to test Penguin Watch translations, since I vaguely remember that readymade might have hacked the `zooniverse` variable to make those work (could be wrong on this.)

Is there any reason not to just do this in zooniverse/Zooniverse ? eg. `module.exports = window.zooniverse.Api` here https://github.com/zooniverse/Zooniverse/blob/master/src/lib/api.coffee#L53

**Comment by eatyourgreens** [comment]
Penguin Watch translations look fine to me too, so this looks good to merge.

**Comment by parrish** [comment]
I approached it from readymade since it was defining/overriding the modules too.  Mind releasing a version bump?

**Comment by eatyourgreens** [comment]
@parrish published as 1.2.0. Cheers!

**Pull request merged**
